name: GitHub Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: prithvi-01x
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # THEME
          config_theme: matrix
          config_display: large
          config_padding: 0, 8

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 6

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C

          # Stars
          plugin_stars: yes

          # Calendar
          plugin_isocalendar: yes

          # Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes

          # Repositories
          plugin_repositories: yes
