name: GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: prithvi-01x
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # ğŸ¨ theme
          config_display: large
          config_padding: 0, 8

          # ğŸ“… calendar
          plugin_isocalendar: yes

          # ğŸ§  languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%

          # ğŸ”¥ activity graph
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # ğŸ† achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # â­ stars
          plugin_stars: yes

          # ğŸ“Š lines changed
          plugin_lines: yes

          # ğŸ“… habits
          plugin_habits: yes
          plugin_habits_from: 200

          # ğŸ snake
          plugin_skyline: yes

          # ğŸ¯ followup
          plugin_followup: yes

          # ğŸ“ˆ repositories
          plugin_repositories: yes
          plugin_repositories_featured: FloatChat

